apiVersion: v1
kind: Namespace
metadata:
  name: key-vault
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-app
  namespace: key-vault
spec:
  selector:
    app: key-vault-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-vault-app-deploy
  namespace: key-vault
  labels:
    app: key-vault-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: key-vault-app
  template:
    metadata:
      labels: 
        app: key-vault-app
    spec:
      containers:
      - name: key-vault-app
        image: betassaalexandre/key-vault:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.2"
          limits:
            memory: "250Mi"
            cpu: "1"
        livenessProbe:
          tcpSocket: 
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3


          